# .github/workflows/feature_pipeline.yml

name: Hourly Feature Pipeline

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run_feature_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run feature pipeline
        run: python -m src.pipelines.feature_pipeline
        env:
          PYTHONPATH:  ${{ github.workspace }}
          MONGO_URI:   ${{ secrets.MONGO_URI }}
          MONGO_DB:    ${{ secrets.MONGO_DB }}
          LAT:         ${{ secrets.LAT }}
          LON:         ${{ secrets.LON }}
          TIMEZONE:    ${{ secrets.TIMEZONE }}